import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";
import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";
import TitleHanlder from "@/components/TitleHanlder";
import { ThemeProvider } from "@/components/ThemeProvide";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  description: "Generated by create next app",
  icons: {
    icon: "/image.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body className="bg-gray-200 min-h-screen flex flex-col md:flex-row lg:flex-row">

      <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >

        
        <TitleHanlder />
        <Sidebar />

        <div className=" flex-col flex-grow flex w-full">
          <Navbar className="hidden md:block " />

          <main className="flex-grow p-4">{children}</main>
        </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
